### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by mrkylesmith** [cccz1/15lreport#1]
Here is your feedback for Lab Report 1:

- [] All relevant URLs written as markdown links
- You should provide a link for changing your password for 15L account (like you did for VScode)
- [] All relevant code examples written with backticks (```)
- You should have all code examples and commands in backticks like this: 
- ```ls```
- ```cd```
- ```pwd```
- ```ssh <youraccount>```
- ```scp <filename>``` (provide the whole command here)
- ```ssh-keygen```
- etc... Just make sure that any commands you reference have backticks around them throughout the report
- [] All screenshots correspond to the described steps
- You should add a screenshot for step 5 and step 6 
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
- Provide a screenshot for this part and explain what you did in the image. 
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
- Good job overall. 
--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by mrkylesmith** [comment]
Under step 1, you should provide the URLs as live markdown links (HERE: download VScode from https://code.visualstudio.com/, then install it.) Make this link live, so that I can click it and it will take me to the VScode download page.  Same goes for any other links you have added in the lab.  

You should also make each section a header.  So 1. 2. 3. etc, should be formatted as markdown headers. 

Please also provide a screenshot to go along with step 5, using the ```ssh-keygen``` command. 

There are also several times throughout the lab report that you use commands without backtick formatting.  Anytime you reference a command you should format it like this:  (example from your lab report) 

Use  ```ssh-keygen``` command to set up the ```ssh``` key to avoid typing password every time you use the ```scp``` command. 

Please make these changes and then submit another regrade request and comment here and I can update your score to full credit.

**Comment by cccz1** [comment]
> 

regrade request submitted.

**Comment by mrkylesmith** [comment]
I see your changes, great job!! I have updated your score.
